<?xml version="1.0"?>
<robot name="intel_d435" xmlns:xacro="http://www.ros.org/wiki/xacro">

      <!-- The following values are approximate, and the camera node
   publishing TF values with actual calibrated camera extrinsic values -->
  <xacro:property name="d435_cam_depth_to_left_ir_offset" value="0.0"/>
  <xacro:property name="d435_cam_depth_to_right_ir_offset" value="-0.050"/>
  <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>

  <!-- The following values model the aluminum peripherial case for the
    D435 camera, with the camera joint represented by the actual
    peripherial camera tripod mount -->
  <xacro:property name="d435_cam_width" value="0.090"/>
  <xacro:property name="d435_cam_height" value="0.025"/>
  <xacro:property name="d435_cam_depth" value="0.02505"/>
  <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>

  <!-- The following offset is relative the the physical D435 camera peripherial
    camera tripod mount -->
  <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
  <xacro:property name="d435_cam_depth_py" value="0.0175"/>
  <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>

  <material name="Aluminum">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>



    <joint name="intel_d435_mount_fixed" type="fixed">
        <origin xyz="${INTEL_D435_MOUNT_X} ${INTEL_D435_MOUNT_Y} ${INTEL_D435_MOUNT_Z}"
                rpy="${INTEL_D435_MOUNT_R} ${INTEL_D435_MOUNT_P} ${INTEL_D435_MOUNT_Y}"/>
        <parent link="${INTEL_D435_MOUNT_LINK}"/>
        <child link="camera_link"/>
    </joint>

    <link name="camera_link">
      <visual>
      <origin xyz="${d435_cam_mount_from_center_offset} 0.0 ${d435_cam_height/2}" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <!-- <box size="${d435_cam_width} ${d435_cam_height} ${d435_cam_depth}"/> -->
	      <mesh filename="package://infi_sim_v1/models/OPTIMUS_robot_001/meshes/d435.dae" />
        </geometry>
        <material name="Aluminum"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${d435_cam_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>

    <!--The following links will be not modeled and displayed.-->
      <!-- camera depth joints and links -->
      <joint name="camera_depth_joint" type="fixed">
        <origin xyz="${d435_cam_depth_px} ${d435_cam_depth_py} ${d435_cam_depth_pz}" rpy="0 0 0"/>
        <parent link="camera_link"/>
        <child link="camera_depth_frame" />
      </joint>
      <link name="camera_depth_frame"/>

      <joint name="camera_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="camera_depth_frame" />
        <child link="camera_depth_optical_frame" />
      </joint>
      <link name="camera_depth_optical_frame"/>

      <!-- camera left IR joints and links -->
      <joint name="camera_left_ir_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_left_ir_offset} 0" rpy="0 0 0" />
        <parent link="camera_depth_frame" />
        <child link="camera_left_ir_frame" />
      </joint>
      <link name="camera_left_ir_frame"/>

      <joint name="camera_left_ir_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="camera_left_ir_frame" />
        <child link="camera_left_ir_optical_frame" />
      </joint>
      <link name="camera_left_ir_optical_frame"/>

      <!-- camera right IR joints and links -->
      <joint name="camera_right_ir_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_right_ir_offset} 0" rpy="0 0 0" />
        <parent link="camera_depth_frame" />
        <child link="camera_right_ir_frame" />
      </joint>
      <link name="camera_right_ir_frame"/>

      <joint name="camera_right_ir_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="camera_right_ir_frame" />
        <child link="camera_right_ir_optical_frame" />
      </joint>
      <link name="camera_right_ir_optical_frame"/>

      <!-- camera color joints and links -->
      <joint name="camera_color_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_color_offset} 0" rpy="0 0 0" />
        <parent link="camera_depth_frame" />
        <child link="camera_color_frame" />
      </joint>
      <link name="camera_color_frame"/>

      <joint name="camera_color_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="camera_color_frame" />
        <child link="camera_color_optical_frame" />
      </joint>
      <link name="camera_color_optical_frame"/>

    <gazebo reference="camera_link">
      <sensor type="depth" name="camera">
            <always_on>true</always_on>
            <update_rate>20.0</update_rate>
            <camera>
              <horizontal_fov>1.0471975512</horizontal_fov>
              <image>
                <format>R8G8B8</format>
                <width>1280</width>
                <height>800</height>
              </image>
              <clip>
                <near>0.05</near>
                <far>8.0</far>
              </clip>
            </camera>
            <plugin name="kinect_camera_controller" filename="libgazebo_ros_openni_kinect.so">
              <robotNamespace>/</robotNamespace>
              <cameraName>camera</cameraName>
              <alwaysOn>true</alwaysOn>
              <updateRate>10</updateRate>
              <imageTopicName>rgb/image_raw</imageTopicName>
              <depthImageTopicName>depth/image_raw</depthImageTopicName>
              <pointCloudTopicName>depth/points</pointCloudTopicName>
              <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
              <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
              <frameName>camera_depth_optical_frame</frameName>
              <baseline>0.1</baseline>
              <pointCloudCutoff>0.4</pointCloudCutoff>
              <distortionK1>0.00000001</distortionK1>
              <distortionK2>0.00000001</distortionK2>
              <distortionK3>0.00000001</distortionK3>
              <distortionT1>0.00000001</distortionT1>
              <distortionT2>0.00000001</distortionT2>
              <CxPrime>0</CxPrime>
              <Cx>0</Cx>
              <Cy>0</Cy>
              <focalLength>0</focalLength>
             <hackBaseline>0</hackBaseline>
            </plugin>
          </sensor>
    </gazebo>

</robot>